### ISSUE TITLE
compare .gif image giving error Cannot read property 'width' of null

### ISSUE THREAD

**Issue by KaranbeerKaur** [lksv/node-resemble.js#30]
If I compare .png images my code is working fine. But If I compare .gif images it gives below error

TypeError: Cannot read property 'width' of null
    at /Users/karanbeer.kaur/node_modules/node-resemble-js/resemble.js:120:26
    at .<anonymous> (/Users/xyz/node_modules/pngjs/lib/png.js:80:7)
    at g (events.js:286:16)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at ParserAsync._handleError (/Users/xyz/node_modules/pngjs/lib/parser-async.js:34:8)
    at Parser._parseSignature (/Users/xyz/node_modules/pngjs/lib/parser.js:51:12)
    at ChunkStream._processRead (/Users/xyz/node_modules/pngjs/lib/chunkstream.js:174:13)

Kindly help how i can resolve this issue. 
If .gif format is not supported by node-resemeble.js then please mention list of supported image formats in readme.md.

**Comment by mirzazeyrek** [comment]
I don't think comparing gif images would be possible or even needed. 

Also please kindly explain what kind of output do you expect when comparing animated gifs?

**Comment by KaranbeerKaur** [comment]
when I am comparing attached images on this(https://huddle.github.io/Resemble.js/) link it is showing me output image, same I want from code to give output image
![3174602-onglyza_pdf](https://cloud.githubusercontent.com/assets/16605677/20377351/a4acb244-acb4-11e6-9dd2-0233138c772e.gif)
![3174602-onglyza_pdf](https://cloud.githubusercontent.com/assets/16605677/20377353/a93a2f58-acb4-11e6-987e-511744862440.gif)

**Comment by KaranbeerKaur** [comment]
Is this works only for PNG files? I am giving .jpg image for compare. Still getting same error.
```
Cannot read property 'width' of null
    at /Users/karanbeer.kaur/node_modules/node-resemble-js/resemble.js:120:26
```

**Comment by mirzazeyrek** [comment]
Could you please share the images and your code ?

**Comment by KaranbeerKaur** [comment]
Hi,

I have shared  code and images. please let me know, what changes I need to make. 
![yy](https://cloud.githubusercontent.com/assets/16605677/20740314/f352d986-b6e7-11e6-8b62-b9440f4d3fb6.jpg)
![yy](https://cloud.githubusercontent.com/assets/16605677/20740315/f51244aa-b6e7-11e6-9252-2579b387ad85.jpg)



```

var express = require('express');
var fs = require('fs');
//var resemble = require('node-resemble-js');
var resemble = require('node-resemble-v2');
resemble.outputSettings({
              errorColor: {
                red: 0,
                green: 0,
                blue: 255
             },
            errorType: 'flat',
            transparency: 1,
            largeImageThreshold: 1200
           

});
var app = express();
var router = express.Router();
var HOST = "localhost";
var PORT = 3306;
var WEBSERVICE_PORT = process.env.PORT || 8443;
var bodyParser = require("body-parser");

var server = app.listen(WEBSERVICE_PORT, function() {
//var server = https.createServer(options,app).listen(WEBSERVICE_PORT, function() {

    console.log('Ready');
    var host = server.address().address
    var port = server.address().port

    console.log("Example app listening at http://%s:%s", host, port)
});
app.use(bodyParser.json());
app.post('/compare', function (req, res) {
    console.log("params==" + req.params);
    var requestJson = req.body;
     console.log("jsondata==" +JSON.stringify(requestJson));
    var filePath1 = requestJson.filePathone;
    var filePath2 = requestJson.filepathtwo;
    compareImages(filePath1,filePath2,res);	  
});


//router.get('/compare', function(req, res, next) {
//    compareImages(res);
//});

var compareImages = function (filePath1,filePath2,res) {
    var fileData1 = fs.readFileSync(filePath1);
    var fileData2 = fs.readFileSync(filePath2);
   //resemble.;

    var diff = this.resemble(fileData1).compareTo(fileData2).onComplete(function(data){
            var df = "/xyz/diff.png";
           // console.log("kk="+JSON.stringify(data));
            //data.getDiffImage().pack().pipe(fs.createWriteStream(df));
            
            console.log("%="+ data.misMatchPercentage);
            var png = data.getImageDataUrl();
             console.log("kk="+png);
            //var png = data.getDiffImage();
            var buf = new Buffer([])
            var strm = png.pack()
            strm.on('data', function (dat) {
              buf = Buffer.concat([buf, dat])
            })
            strm.on('end', function() {
              fs.writeFile(df, buf, null, function (err) {
                if (err) {
                 throw 'error writing file: ' + err;
                }
                console.log('file written');
                res.sendFile(df)
              })
            })
        });
      console.log("diff="+JSON.stringify(diff)); 
   
};

```

**Comment by KaranbeerKaur** [comment]
I have given https://github.com/lksv/node-resemble.js/blob/master/example/People2.jpg
https://github.com/lksv/node-resemble.js/blob/master/example/People.jpg these images also still getting same error

**Comment by KaranbeerKaur** [comment]
Please update and waiting for reply

**Comment by sdkevorkian** [comment]
Hi, 
I am having this same issue,
`TypeError: Cannot read property 'width' of null
`
 trying to compare two .jpg files. I am learning still and experimenting. here is the code I have:

`
app.get('/test2', function(req, res) {
    var fileData1 = fs.readFileSync('spaniel.jpg');
    var fileData2 = fs.readFileSync('me.jpg');
    resemble(fileData1).compareTo(fileData2)
        //.ignoreAntialiasing()
        //.ignoreColors()
        .onComplete(function(data) {
            res.send(data);
        });
});

`

**Comment by omonk** [comment]
@sdkevorkian I've found this issue thats been closed, bit late I know but it appears that when using a jpg you can get add the 'path/to/file' route as a string. See issue [here](https://github.com/lksv/node-resemble.js/issues/5) along with [commit](https://github.com/lksv/node-resemble.js/commit/55fb5c4455a44279fb5dabf347996cdee3bde2bd)
