### ISSUE TITLE
height missing? 

### ISSUE THREAD

**Issue by alphacentory** [lksv/node-resemble.js#5]
I am passing the buffer returned after fs.readFileSync

TypeError: Cannot read property 'width' of null
    at /Users/hulk/github/gameclash/tweetbot/node_modules/node-resemble-js/resemble.js:119:30
    at null.<anonymous> (/Users/hulk/github/gameclash/tweetbot/node_modules/node-resemble-js/node_modules/pngjs/lib/png.js:91:13)
    at g (events.js:180:16)
    at emit (events.js:95:17)
    at emit (events.js:117:20)
    at Parser._parseSignature (/Users/hulk/github/gameclash/tweetbot/node_modules/node-resemble-js/node_modules/pngjs/lib/parser.js:87:18)
    at ChunkStream._process (/Users/hulk/github/gameclash/tweetbot/node_modules/node-resemble-js/node_modules/pngjs/lib/chunkstream.js:186:23)
    at ChunkStream.write (/Users/hulk/github/gameclash/tweetbot/node_modules/node-resemble-js/node_modules/pngjs/lib/chunkstream.js:74:10)
    at ChunkStream.end (/Users/hulk/github/gameclash/tweetbot/node_modules/node-resemble-js/node_modules/pngjs/lib/chunkstream.js:85:20)
    at PNG.end (/Users/hulk/github/gameclash/tweetbot/node_modules/node-resemble-js/node_modules/pngjs/lib/png.js:105:18)

**Comment by mirzazeyrek** [comment]
@lksv @SlevinT I have made the pull request for jpeg support. Please check the pull request:

https://github.com/lksv/node-resemble.js/pull/25/commits/55fb5c4455a44279fb5dabf347996cdee3bde2bd
